### ISSUE TITLE
Workbase does not work with KGMS (AWS)

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/workbase#145]
## Description

Trying to connect to AWS:
![image](https://user-images.githubusercontent.com/6430514/58091601-f15fc200-7bc1-11e9-967d-cd5714d72500.png)

We have verified using `grakn console` that Grakn is actually up and running

## Environment

1. Grakn version: Grakn KGMS 1.5.2 - AWS
3. Workbase version: 1.2.1 and 1.2.2
4. OS of Workbase: Mac OS 10
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Deploy on AWS
2. Open Workbase
3. Error - Grakn is not running

 
## Additional information

Let's make sure to test these things!

**Comment by Irtazaraza** [comment]
Tested and issue does not occur

**Comment by sorsaffari** [comment]
@Irtazaraza we need to make an issue for adding the necessary tests, as marco has suggested.

**Comment by sorsaffari** [comment]
@marco-scoppetta given that workbase uses client nodejs to instantiate a client, I think testing the connection between the client and KGMS on AWS, falls under the integration tests of client nodejs (and similarly for the other clients). appreciate it if you could file an issue on the clients so that we won't forget the need for such test.
