### ISSUE TITLE
Use Yarn instead of NPM

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/workbase#172]
## Problem to Solve
As explained in [this issue](https://github.com/bazelbuild/rules_nodejs/issues/948), `npm_install` does not work well with Bazel.

## Current Workaround
N/A

## Proposed Solution
Use `yarn` in place of `npm` and `yarn_install` in place of `npm_install`.

**Comment by sorsaffari** [comment]
@vmax need your help on this 🙏 

Here is what I have tried so far:
- used [`electron-rebuild`](https://github.com/electron/electron-rebuild) instead of `install-node-electron.sh`
https://github.com/sorsaffari/workbase/blob/fix-sub-thing/package.json#L161

- updated `WORKSPACE` to use `yarn_install`:
https://github.com/sorsaffari/workbase/blob/fix-sub-thing/WORKSPACE#L43-L62

here is the last run of workbase CI, wich has failed:
https://circleci.com/gh/graknlabs/workbase/2626?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
